# -*- coding: utf-8 -*-
"""mln_gnn_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GH_1dnQk4DC-ufWwUSxHbLDhDaGeXgTJ
"""

# !pip install -r /content/drive/My Drive/dataset/code/requirements.txt

# !pip install wordninja

# Commented out IPython magic to ensure Python compatibility.
import pickle
def upload_file_to_drive(file, destination='/content/drive/My Drive/dataset'):
    """
    Uploads a file to Google Drive.

    Args:
    - file (str): The filename or filepath of the file to upload.
    - destination (str): The destination directory in Google Drive.
    """
#     %mv "{file}" "{destination}"

def save_variable(var, filename, destination=None):
    """
    Saves a variable to a file and optionally uploads it to Google Drive.

    Args:
    - var: The variable to save.
    - filename (str): The filename to save the variable to.
    - destination (str): Optional. The destination directory in Google Drive.
    """
    with open(filename, 'wb') as f:
        pickle.dump(var, f)
    if destination:
        upload_file_to_drive(filename, destination=destination)
        print(f"File Uploaded to {destination}")
    else:
        print(f"Variable Saved as {filename}. Use 'upload_file_to_drive' to save in drive.")

def load_variable(filename: str):
    """
    Loads a variable from a file.

    Args:
    - filename (str): The filename to load the variable from.

    Returns:
    - The variable loaded from the file.
    """
    with open(filename, 'rb') as f:
        return pickle.load(f)

import pandas as pd

def load_and_process_dataset(dataset_filename):
    """
    Load and process a dataset from Google Drive.

    Args:
    - dataset_filename (str): The filename of the dataset to load.

    Returns:
    - pd.DataFrame: The processed DataFrame containing the dataset.
    """
    # Define the file paths for the datasets
    dataset_files = {
        "founta_dataset.csv": "/content/drive/My Drive/dataset/founta_dataset.csv",
        "__founta_dataset__.csv": "/content/drive/My Drive/dataset/__founta_dataset__.csv",
        "labeled_data_t_davison.csv": "/content/drive/My Drive/dataset/labeled_data_t_davison.csv"
    }

    # Check if the selected dataset filename is valid
    if dataset_filename not in dataset_files:
        print("Invalid dataset filename selected.")
        return None
    else:
        # Load the dataset into a pandas DataFrame
        dataset_df = pd.read_csv(dataset_files[dataset_filename])

        # Shuffle the dataset rows randomly
        dataset_df = dataset_df.sample(frac=1, random_state=1)

        # Reset the index of the DataFrame
        dataset_df.reset_index(drop=True, inplace=True)

        # Rename columns for clarity
        dataset_df.rename(columns={'Tweet text  Label   Votes for the majority label': 'tweets',
                                    'Unnamed: 1': 'label',
                                    'Unnamed: 2': 'major'}, inplace=True)

        print(f"Dataset '{dataset_filename}' loaded successfully.")
        return dataset_df

# Example usage:
# selected_dataset_filename = "founta_dataset.csv"  # Change this as needed
# loaded_dataset = load_and_process_dataset(selected_dataset_filename)

# You can use the loaded_dataset DataFrame for further analysis or processing

import re
import wordninja
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
nltk.download('stopwords')

tokenizer = nltk.RegexpTokenizer(r"\w+")
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def split_word_and_filter(concatenated_word: str, embeddings: dict) -> list:
    """
    Split a concatenated word into meaningful components and filter out
    words that do not exist in the embeddings.

    Args:
    - concatenated_word (str): The concatenated word to be split.
    - embeddings (dict): Dictionary containing word embeddings.

    Returns:
    - list: A list of split words that exist in the embeddings.
    """
    split_words = wordninja.split(concatenated_word)
    valid_words = [word for word in split_words if word in embeddings]
    return valid_words

def preprocess_text_and_tokenize(text: str, embeddings: dict) -> list:
    """
    Preprocess a text message and tokenize it based on embeddings.

    Args:
    - text (str): The input text message to preprocess and tokenize.
    - embeddings (dict): Dictionary containing word embeddings.

    Returns:
    - list: A list of useful tokens extracted from the preprocessed text.
    """
    cleaned_text = text.lower()
    cleaned_text = re.sub(r'@\w+\b|#\w+\b|https?://\S+', '', cleaned_text)
    cleaned_text = re.sub(r'\b(rt)\b', '', cleaned_text, flags=re.IGNORECASE)
    cleaned_text = re.sub(r'[^a-zA-Z]', ' ', cleaned_text)
    cleaned_text = re.sub(r'\b\w{1}\b', '', cleaned_text)
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    tokens = tokenizer.tokenize(cleaned_text)
    lowercased_tokens = [t.lower() for t in tokens]
    lemmatized_tokens = [lemmatizer.lemmatize(t) for t in lowercased_tokens]
    filtered_tokens = [t for t in lemmatized_tokens if t not in stop_words]

    useful_tokens = []
    for t in filtered_tokens:
        if t in embeddings:
            useful_tokens.append(t)
        else:
            useful_tokens.extend(split_word_and_filter(t, embeddings))

    return useful_tokens

import re
import wordninja

def process_tweet_hashtags(tweet_series, embedding_dictionary):
    """
    Process hashtags from a series of tweets, including splitting concatenated hashtags into meaningful words.

    Args:
    - tweet_series (pandas.Series): Series containing tweets.
    - embedding_dictionary (dict): Dictionary containing word embeddings.

    Returns:
    - list: A list of processed hashtags.
    """
    def get_hashtags(tweet):
        hashtags = re.findall(r'#(\w+)', tweet)
        return hashtags

    def remove_numeric_hashtags(hashtags):
        return [tag for tag in hashtags if not tag.isdigit()]

    def split_concatenated_hashtags_to_words(concatenated_words):
        words_to_split = [word for word in concatenated_words if word not in embedding_dictionary.keys()]
        split_words_list = [wordninja.split(str(word)) for word in words_to_split]
        return split_words_list

    def remove_empty_strings(lst):
        return [word for word in lst if word != "'"]

    def iterate(item):
        if(len(item)>0 and type(item[0])!=list):
          return item
        _item = []
        for i in item:
          _item.extend(iterate(i))
        return _item

    hashtags = tweet_series.apply(get_hashtags)
    hashtags = hashtags.apply(remove_numeric_hashtags)
    hashtags = hashtags.apply(split_concatenated_hashtags_to_words)
    hashtags = hashtags.apply(remove_empty_strings)
    hashtags = [i for i in hashtags]
    hashtags = [iterate(i) for i in hashtags]
    return hashtags

import spacy

# Load the English language model
nlp = spacy.load('en_core_web_sm')

def extract_aspect_words(sentence):
    """
    Extract aspect words (nouns, proper nouns, and adjectives) from a given sentence using spaCy.

    Args:
    - sentence (str): The input sentence to extract aspect words from.

    Returns:
    - aspect_words (list): List of aspect words extracted from the sentence.
    """
    # Parse the sentence using spaCy
    doc = nlp(sentence)

    # Initialize a list to store aspect words
    aspect_words = []

    # Iterate through each token in the parsed sentence
    for token in doc:
        # Check if the token is a noun, proper noun, or adjective
        if token.pos_ in ['NOUN', 'PROPN', 'ADJ']:
            # Add the token to the list of aspect words
            aspect_words.append(token.text)

    return aspect_words



import torch

def get_default_device():
    """
    Pick GPU if available, else CPU.

    Returns:
    - torch.device: Chosen device (GPU if available, else CPU).
    """
    return torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

def to_device(data, device):
    """
    Move tensor(s) to the chosen device.

    Args:
    - data: Tensor or list/tuple of tensors to move to the device.
    - device (torch.device): Target device for the data.

    Returns:
    - Tensor or list/tuple of tensors: Data moved to the chosen device.
    """
    if isinstance(data, (list, tuple)):
        return [to_device(x, device) for x in data]
    return data.to(device, non_blocking=True)

# Get the default device
device = get_default_device()

import numpy as np

def generate_sentence_vectors(tokenized_sentences: list, word_embeddings: dict):
    """
    Generate sentence vectors from tokenized sentences using word embeddings.

    Args:
    - tokenized_sentences (list): List of tokenized sentences.
    - word_embeddings (dict): Dictionary containing word embeddings.

    Returns:
    - sentence_vectors (list): List of sentence vectors.
    """
    sentence_vectors = []

    # Handle case when tokenized_sentences is empty
    if not tokenized_sentences:
        return [np.zeros_like(word_embeddings['a'])]

    # Iterate through each tokenized sentence
    for sentence in tokenized_sentences:
        vector_sum = np.zeros_like(word_embeddings['a'])
        word_count = 0

        # Calculate the sum of word vectors in the sentence
        for word in sentence:
            if word in word_embeddings:
                vector_sum += word_embeddings[word]
                word_count += 1

        # Calculate the average sentence vector
        if word_count > 0:
            average_vector = vector_sum / word_count
        else:
            average_vector = np.zeros_like(word_embeddings['a'])

        sentence_vectors.append(average_vector)

    return sentence_vectors

def batch_generator(tweets=[], hashtags=[], labels=[], batch_size=1000):
    """
    Generate batches of data from provided lists of tweets, hashtags, and labels.

    Args:
    - tweets (list): List of tweets.
    - hashtags (list): List of hashtags.
    - labels (list): List of labels.
    - batch_size (int): Size of each batch.

    Yields:
    - tuple: Batch of tweets, hashtags, and labels.
    """
    # Iterate through the data lists in batch sizes
    for i in range(0, len(tweets), batch_size):
        # Yield a batch of tweets, hashtags, and labels
        yield tweets[i:i+batch_size], hashtags[i:i+batch_size], labels[i:i+batch_size]